ecomtake2/ecomapp/urls.py
from django.urls import path
from .views import *

app_name = "ecomapp"
urlpatterns = [
    path("", HomeView.as_view(), name = "home"),
    path("about/", AboutView.as_view(), name = "about"),
    path("contact-us/", ContactView.as_view(), name = "contact"),
    path("all-products/", AllProductsView.as_view(), name = "allproducts"),
    path("product/<slug:slug>/", ProductDetailView.as_view(), name = "productdetail"), # slug- dyn var
    path("add-to-cart-<int:pro_id>/", AddToCartView.as_view(), name = "addtocart"),
    path("my-cart/", MyCartView.as_view(), name = "mycart"),
    path("manage-cart/<int:cp_id>/", ManageCartView.as_view(), name = "managecart"),
    path("empty-cart/", EmptyCartView.as_view(), name = "emptycart"),
    path("checkout/", CheckoutView.as_view(), name = "checkout"),
    path("customerregistration/", CustomerRegistrationView.as_view(), name = "customerregistration"),
    path("customerlogout/", CustomerLogoutView.as_view(), name = "customerlogout"),
    path("customerlogin/", CustomerLoginView.as_view(), name = "customerlogin"),
    path("customerprofile/", CustomerProfileView.as_view(), name = "customerprofile"),
    path("profile/order-<int:pk>/", CustomerOrderDetailView.as_view(), name = "customerorderdetail"),

    path("search/", SearchView.as_view(), name = "search"),


    path("admin-login/", AdminLoginView.as_view(), name = "adminlogin"),
    path("admin-home/", AdminHomeView.as_view(), name = "adminhome"),

]


ecomtake2/ecomtake2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("ecomapp.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ecomtake2/ecomapp/models.py
from django.contrib.auth.models import User
from django.db import models

class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=50)
    image = models.ImageField(upload_to="admins")
    phone = models.CharField(max_length=20)

    def __str__(self):
        return self.user.username

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=200)
    address = models.CharField(max_length=200, null=True, blank=True)
    joined_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name

class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title
    
class Product(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE) # 1-m Product to Category
    image = models.ImageField(upload_to="products")
    marked_price = models.FloatField()
    selling_price = models.FloatField()
    description = models.TextField()
    # warranty = models.CharField(max_length=300, null=True, blank=True)
    # return_policy = models.CharField(max_length=300, null=True, blank=True)
    view_count = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title

class Cart(models.Model):
    customer = models.ForeignKey(
        Customer, on_delete=models.SET_NULL, null=True, blank=True) #1-1 Customer to Cart
    total = models.FloatField(default = 0)
    created_at =  models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Cart: " + str(self.id)

class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE) # 1-m Cart to Product
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rate = models.FloatField()
    quantity = models.PositiveIntegerField()
    subtotal = models.FloatField()

    def __str__(self):
        return "Cart: " + str(self.cart.id) + "CartProduct: " + str(self.id)

ORDER_STATUS = ( # first value in db, second in form
    ("Order Placed", "Order Placed"),
    ("Order Processing", "Order Processing"),
    ("Delivery in Progress", "Delivery in Progress"),
    ("Order Complete", "Order Complete"),
    ("Order Cancelled", "Order Cancelled"),
)

class Order(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    ordered_by = models.CharField(max_length=200)
    shipping_address = models.CharField(max_length=200)
    phone = models.CharField(max_length=10)
    email = models.EmailField(null=True, blank=True)
    subtotal = models.FloatField()
    discount = models.FloatField()
    total = models.FloatField()
    order_status = models.CharField(max_length=50, choices=ORDER_STATUS)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Order: " + str(self.id)

ecomtake2/templates/about.html
{% extends 'base.html' %}

{% block title %}About Us{% endblock %}

{% block content %}
    <h1>Welcome to our site!</h1>
{% endblock %}

ecomtake2/templates/addtocart.html
{% extends 'base.html' %}

{% block title %} All Products {% endblock %}

{% block content %}
<div class="container">
    <h3>Product added to cart</h3>
    <hr>
</div>
<div>
    <div class="row">
        <div class="col-md-6">
            <pre></pre>
            <a href="{% url 'ecomapp:home' %}"class="btn btn-outline-secondary">Continue Shopping</a>
        </div>
        <div class="col-md-6">
            <pre></pre>
            <a href="{% url 'ecomapp:mycart' %}"class="btn btn-outline-secondary">My Cart</a>
        </div>
    </div>
</div>
    <!--add a "continue shopping" button and a "view cart" button-->
{% endblock %}

ecomtake2/templates/allproducts.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %} All Products {% endblock %}

{% block content %}
<div class="container">
    <h3>All Products</h3><hr>
    {% for c in allcategories %}
    <h4>{{c.title}}</h4>
    <div class="row">
        {% for p in c.product_set.all %}
        <div class="col-md-6"><!--style="border: 1px solid black"-->
            <div class="m-6">
                <h3>{{p.title}}</h3>
                <a href="{% url 'ecomapp:productdetail' p.slug %}">
                    <img src="{{p.image.url}}" alt="" width="200px" class="image-fluid" style="height:2500; object-fit: cover;">
                </a>
                <p class="mt-3"><!--MSRP: $<strike>{{marked_price}}</strike> -->${{p.selling_price|floatformat:2|intcomma}}</p>
                <a href="{% url 'ecomapp:addtocart' p.id %}" class="btn btn-outline-info"><b>Add to Cart</b></a>
                <hr>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endfor %}
</div>
{% endblock %}

ecomtake2/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
</head>
<body class="text-center">
    <div class="container">
        <pre></pre>
        <a href="/" class="btn btn-outline-secondary">Home</a><!--href="{% url 'ecomapp:home' %}"-->
        <a href="/about/" class="btn btn-outline-secondary">About Us</a>
        <a href="/contact-us/" class="btn btn-outline-secondary">Contact Us</a>
        <a href="/all-products/" class="btn btn-outline-secondary">Categories</a>
        <a href="/my-cart/" class="btn btn-outline-secondary">My Cart</a>

        {% if request.user.customer %}
        <a href="/customerprofile/" class="btn btn-outline-secondary">My Profile</a>
        <a href="/customerlogout/" class="btn btn-outline-secondary">Logout</a>
        Welcome {{request.user.username}}
        {% else %}
        <a href="/customerregistration/" class="btn btn-outline-secondary">Register</a>
        <a href="/customerlogin/" class="btn btn-outline-info">Login</a>
        {% endif %}
        <hr>
        <div class="container">
            <div class="row">
                <div class="col-lg-6 mx-auto">
                    <form action="{% url 'ecomapp:search' %}" method="GET"> <!--or POST method which is more secure-->
                        <input type="text" name="keyword" placeholder="Search..." required>
                        <button class="btn btn-info btn-sm fw-bold">Search</button>
                    </form>
                </div>
            </div>
        </div>
        <pre></pre>
    </div>
    {% block content %}
    {% endblock %}
</body>
</html>

ecomtake2/templates/checkout.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %} Checkout {% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h3>Cart Contents</h3>
            <a href="{% url 'ecomapp:mycart' %}" class="btn btn-outline-secondary">My Cart</a>
            <table class="table">
                <div class="col-md-8">
                <thead>
                    <tr>
                        <th>Product</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in cart.cartproduct_set.all %}
                    <div class="row">
                        <tr>
                            <td style="vertical-align:middle">
                                <a href="{% url 'ecomapp:productdetail' cp.product.slug %}">
                                    <img src="{{cp.product.image.url}}" alt="" width="75px" class="image-thumbnail">
                                </a><b>{{cp.product.title}}</b>
                            </td>
                            <td style="vertical-align:middle">${{cp.rate}}</td>
                            <td style="vertical-align:middle">{{cp.quantity}}</td>
                            <td style="vertical-align:middle">${{cp.subtotal|floatformat:2}}</td>
                        </tr>
                        {% endfor %}
                        <tr>
                            <th colspan = "3" style="text-align:right">Subtotal</th>
                            <th>${{cart.total|floatformat:2}}</th>
                        </tr>
                    </div>
                </tbody>
                </div>
            </table>
        </div>
        <div class="col-md-6">
            <h3>Checkout Form</h3>
            <form action="" method = "POST">
                {% csrf_token %}
                {{form.as_p}}
                <!-- not used <a href=""class="btn btn-outline-info"><b>Place Order</b></a> -->
                <!-- <button class="btn btn-info"><b>Place Order</b></button> -->
                
                <div class="box-element hidden" id="payment-info">
                    <small>Paypal Options</small>
                    <div id="paypal-button-container"></div>
                </div>
                <script src="https://www.paypal.com/sdk/js?client-id=Aeg2A63v6LpSFGYNL-k6VCnZ26QU5Q1DpjHwrzWtQWgHh6ubOoR5E7PuVo9Hhq0xVhPqc8b0dq2HeD8A&currency=USD&disable-funding=credit">//&disable-funding=credit to disable a certain button</script> 
                <script>
                    var total = '{{order.cart.total}}'
                    // Render the PayPal button into #paypal-button-container
                    paypal.Buttons({
                        style:{
                            color: 'blue',
                            shape: 'pill',
                        },
                        // Set up the transaction
                        createOrder: function(data, actions) {
                            return actions.order.create({
                                purchase_units: [{
                                    amount: {
                                        value: parseFloat(total).toFixed(2)
                                    }
                                }]
                            });
                        },
                        // Finalize the transaction
                        onApprove: function(data, actions) {
                            return actions.order.capture().then(function(orderData) {
                                submitFormData()
                                // Successful capture! For demo purposes:
                                console.log('Capture result', orderData, JSON.stringify(orderData, null, 2));
                                var transaction = orderData.purchase_units[0].payments.captures[0];
                                
                                // default alert when transaction complete
                                // alert('Transaction '+ transaction.status + ': ' + transaction.id + '\n\nSee console for all available details');

                                // Replace the above to show a success message within this page, e.g.
                                // const element = document.getElementById('paypal-button-container');
                                // element.innerHTML = '';
                                // element.innerHTML = '<h3>Thank you for your payment!</h3>';
                                // Or go to another URL:  actions.redirect('thank_you.html');
                            });
                        }
                    }).render('#paypal-button-container');
                </script>
            </form>
        </div>
    </div>
</div>
{% endblock %}

ecomtake2/templates/contactus.html
{% extends 'base.html' %}

{% block title %}Contact Us{% endblock %}

{% block content %}
    <h1>Contact Information</h1>
    <p>(919)608-2251</p>
    <p>emchesson@aggies.ncat.edu</p>
{% endblock %}

ecomtake2/templates/customerlogin.html
{% extends 'base.html' %}

{% block title %}Customer Login{% endblock %}

{% block content %}
<style>
    .errorlist{
        color: rgb(0, 123, 154)
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h3>Customer Login</h3>
            <form action="" method="POST"> 
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-outline-info btn-sm">
                    <b>Submit</b>
                </button>
                {% if error %}
                <p style="color:rgb(255, 0, 0)">{{error}}</p>
                {% endif %}
            </form>
            <p>New user?   <a href="{% url 'ecomapp:customerregistration' %}{% if request.GET.next %}?next={{request.GET.next}}{% endif %}">Register</a></p>
        </div>
    </div>
</div>

{% endblock %}

ecomtake2/templates/customerorderdetail.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %}Order Detail{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <h3>Order Details</h3><hr>
            <p><span class="fw-bold">Order ID: </span>ORDER#_{{order.id}}</p>
            <p><span class="fw-bold">Order Status: </span>{{order.order_status}}</p>
            <p><span class="fw-bold">Ordered On: </span>{{order.created_at}}</p>
            <p><span class="fw-bold">Ordered By: </span>{{order.ordered_by}}, {{order.phone}}</p>
            <p><span class="fw-bold">Shipping Address: </span>{{order.shipping_address}}</p>

            <h4>Ordered Items</h4><hr>
            <table class="table">
                <thead>
                    <tr>
                        <th>Product</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in order.cart.cartproduct_set.all %}
                    <tr>
                        <div class="row">
                            <td style="vertical-align:middle">
                                <a href="{% url 'ecomapp:productdetail' cp.product.slug %}">
                                    <img src="{{cp.product.image.url}}" alt="" width="75px" class="image-thumbnail">
                                </a><b>{{cp.product.title}}</b>
                            </td>
                            <td style="vertical-align:middle">${{cp.rate|floatformat:2|intcomma}}</td>
                            <td style="vertical-align:middle">{{cp.quantity}}</td>
                            <td style="vertical-align:middle">${{cp.subtotal|floatformat:2|intcomma}}</td>
                            <td style="vertical-align:middle"></td>
                        </div>
                    </tr>
                {% endfor %}
                <tr>
                    <th colspan = "3" style="text-align:right">Total</th>
                    <th>${{order.cart.total|floatformat:2|intcomma}}</th>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

ecomtake2/templates/customerprofile.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %}My Profile{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <h3>Customer Information</h3><hr>
            <p><span class="fw-bold">Name: </span>{{customer.full_name}}</p>
            <p><span class="fw-bold">Username: </span>{{customer.user.username}}</p>
            <p><span class="fw-bold">Email: </span>{{customer.user.email}}</p>
            <p><span class="fw-bold">Address: </span>{{customer.address}}</p>
            <p><span class="fw-bold">Phone Number: </span>{{customer.phone}}</p>
        </div>
        <div class="col-md-8">
            <h3>Previous Orders</h3>
            <hr>
            <table class="table">
                <thead>
                    <tr>
                        <th>Order ID</th>
                        <th>Amount</th>
                        <th>Ordered On</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    {% for o in orders %}
                    <tr>
                        <td><a href="{% url 'ecomapp:customerorderdetail' o.pk %}">ORDER#_{{o.id}}</a></td>
                        <td>${{o.total|floatformat:2|intcomma}}</td>
                        <td>{{o.created_at}}</td><!--|timesince-->
                        <td>{{o.order_status}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}

ecomtake2/templates/customerregistration.html
{% extends 'base.html' %}

{% block title %}Customer Registration{% endblock %}

{% block content %}
<style>
    .errorlist{
        color: rgb(0, 123, 154)
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h3>Customer Registration Form</h3>
            <form action="" method="POST"> 
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-outline-info btn-sm"><b>Submit</b></button>
            </form>
            <p>Existing user?   <a href="{% url 'ecomapp:customerlogin' %}">Login</a></p>
        </div>
    </div>
</div>

{% endblock %}

ecomtake2/templates/home.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="container">
    <h1 class="text-center">JBE Outfitters</h1>
    <hr>
    <div class="row mt-3">
        {% for p in product_list %}
        <div class="col-md-3"><!--style="border: 1px solid black"-->
            <div class="m-6">
                <h3>{{p.title}}</h3>
                <a href="{% url 'ecomapp:productdetail' p.slug %}">
                    <img src="{{p.image.url}}" alt="" width="200px" class="image-fluid" style="height:2500; object-fit: cover;">
                </a>
                <p class="mt-3"><!--MSRP: $<strike>{{marked_price}}</strike> -->${{p.selling_price|floatformat:2|intcomma}}</p>
                <a href="{% url 'ecomapp:addtocart' p.id %}" class="btn btn-outline-info"><b>Add to Cart</b></a>
                <hr>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

ecomtake2/templates/mycart.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %} My Cart {% endblock %}

{% block content %}
<div class="container">
    <h4>Cart Contents</h4><hr>
    {% if cart.cartproduct_set.all %}
    <table class="table">
        <div class="col-md-8">
        <thead>
            <tr>
                <th>Product</th>
                <th>Rate</th>
                <th>Quantity</th>
                <th>Subtotal</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for cp in cart.cartproduct_set.all %}
            <div class="row">
                <tr>
                    <td style="vertical-align:middle">
                        <a href="{% url 'ecomapp:productdetail' cp.product.slug %}">
                            <img src="{{cp.product.image.url}}" alt="" width="75px" class="image-thumbnail">
                        </a><b>{{cp.product.title}}</b>
                    </td>
                    <td style="vertical-align:middle">${{cp.rate|floatformat:2|intcomma}}</td>
                    <td style="vertical-align:middle">{{cp.quantity}}   
                        <a href="{% url 'ecomapp:managecart' cp.id %}?action=increase" class="btn btn-outline-secondary btn-sm"> ⮝ </a>
                        <a href="{% url 'ecomapp:managecart' cp.id %}?action=decrease" class="btn btn-outline-secondary btn-sm"> ⮟ </a>
                    </td>
                    <td style="vertical-align:middle">${{cp.subtotal|floatformat:2|intcomma}}</td>
                    <td style="vertical-align:middle">
                        <a href="{% url 'ecomapp:managecart' cp.id %}?action=remove" class="btn btn-outline-secondary"><b>Remove</b></a>
                    </td>
                </tr>
                {% endfor %}
                <tr>
                    <th colspan = "3" style="text-align:right">Subtotal</th>
                    <th>${{cart.total|floatformat:2|intcomma}}</th>
                    <th>
                        <a href="{% url 'ecomapp:emptycart' %}"class="btn btn-outline-secondary">
                            Empty Cart
                        </a>
                    </th>
                </tr>
            </div>
        </tbody>
        </div>
    </table>
    <tr>
        <th>
            <a href="{% url 'ecomapp:checkout' %}"class="btn btn-outline-info btn-lg btn-block">
                <b>Checkout</b>
            </a>
        </th>
    </tr>
    {% endif %}
    {% if not cart.cartproduct_set.all %}
    <div>
        <h4>No Items in Cart</h4>
        <pre></pre>
        <a href="{% url 'ecomapp:home' %}"class="btn btn-outline-secondary">Continue Shopping</a>
    </div>
    {% endif %}
</div>
{% endblock %}

ecomtake2/templates/productdetail.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %} {{product.title}} {% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{product.image.url}}" alt="" class="img-fluid">
        </div>
        <div class="col-md-6">
            <h3>{{product.title}}</h3><hr>
            <h4 color="red"><b>${{product.selling_price|floatformat:2|intcomma}}</b></h4>
            <h5><strike>${{product.marked_price|floatformat:2|intcomma}}</strike></h5>
            <a href="{% url 'ecomapp:addtocart' product.id %}" class="btn btn-outline-info"><b>Add to Cart</b></a>
            <hr>
            <p align="justify">{{product.description}}</p><!--<p class="text-info"></p? for blue highlight-->
        </div>
    </div>
</div>
{% endblock %}

ecomtake2/templates/search.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %}Search{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            {% if results %}
            <h3>Search results for "<span class="text-info">{{request.GET.keyword}}</span>"</h3>
            <hr>
            {% for r in results %}
            <div class="col-md-6"><!--style="border: 1px solid black"-->
                <div class="m-6">
                    <h3>{{r.title}}</h3>
                    <a href="{% url 'ecomapp:productdetail' r.slug %}">
                        <img src="{{r.image.url}}" alt="" width="200px" class="image-fluid" style="height:2500; object-fit: cover;">
                    </a>
                    <p class="mt-3"><!--MSRP: $<strike>{{marked_price}}</strike> -->${{r.selling_price|floatformat:2|intcomma}}</p>
                    <a href="{% url 'ecomapp:addtocart' r.id %}" class="btn btn-outline-info"><b>Add to Cart</b></a>
                    <hr>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <h3>No results found for "<span class="text-info">{{request.GET.keyword}}</span>"</h3>
            <hr>
            {% endif %}
        </div>
    </div>
{% endblock %}