ecomtake2/ecomapp/urls.py
from django.urls import path
from .views import *

app_name = "ecomapp"
urlpatterns = [
    path("", HomeView.as_view(), name = "home"),
    path("about/", AboutView.as_view(), name = "about"),
    path("contact-us/", ContactView.as_view(), name = "contact"),
    path("all-products/", AllProductsView.as_view(), name = "allproducts"),
    path("product/<slug:slug>/", ProductDetailView.as_view(), name = "productdetail"), # slug- dyn var
    path("add-to-cart-<int:pro_id>/", AddToCartView.as_view(), name = "addtocart"),
    path("my-cart/", MyCartView.as_view(), name = "mycart"),
    path("manage-cart/<int:cp_id>/", ManageCartView.as_view(), name = "managecart"),
    path("empty-cart/", EmptyCartView.as_view(), name = "emptycart"),
    path("checkout/", CheckoutView.as_view(), name = "checkout"),
    path("customerregistration/", CustomerRegistrationView.as_view(), name = "customerregistration"),
    path("customerlogout/", CustomerLogoutView.as_view(), name = "customerlogout"),
    path("customerlogin/", CustomerLoginView.as_view(), name = "customerlogin"),
    path("customerprofile/", CustomerProfileView.as_view(), name = "customerprofile"),
    path("profile/order-<int:pk>/", CustomerOrderDetailView.as_view(), name = "customerorderdetail"),

    path("search/", SearchView.as_view(), name = "search"),


    path("admin-login/", AdminLoginView.as_view(), name = "adminlogin"),
    path("admin-home/", AdminHomeView.as_view(), name = "adminhome"),

]


ecomtake2/ecomtake2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("ecomapp.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ecomtake2/templates/adminpages/adminbase.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <a href="{% url 'ecomapp:adminhome' %}" class="btn btn-outline-secondary">Home</a>
        <a href="{% url 'ecomapp:home' %}" class="btn btn-outline-secondary" target="_blank">Site Home</a>
    </div>
    {% block content %}

    {% endblock %}
</body>
</html>

ecomtake2/templates/adminpages/adminhome.html
{% extends "adminpages/adminbase.html" %}

{% block title %}Admin Home{% endblock %}

{% block content %}
    <div class="container">
        
    </div>
{% endblock %}

ecomtake2/templates/adminpages/adminlogin.html
{% extends 'base.html' %}

{% block title %}Admin Login{% endblock %}

{% block content %}
<style>
    .errorlist{
        color: rgb(0, 123, 154)
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h3>Admin Login</h3>
            <form action="" method="POST"> 
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-outline-info btn-sm">
                    <b>Submit</b>
                </button>
                {% if error %}
                <p style="color:rgb(255, 0, 0)">{{error}}</p>
                {% endif %}
            </form>
        </div>
    </div>
</div>
{% endblock %}